<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>_005Workflows</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9fd56a8b-91fc-4064-a08e-8288ada1f5d4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Projects" Version="2.0.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="CommunityToolkit.VectorData.InMemory" Version="1.0.0" />
    <PackageReference Include="Microsoft.Agents.AI.Foundry" Version="1.5.0" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.15.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

</Project>
